name: Build Meridian
on:
  workflow_dispatch:
    inputs:
      board_env:
        description: 'Select environments'
        required: true
        default: 'Meridian_LITE_ESP32'
        type: choice
        options:
          - Meridian_LITE_ESP32
          - Meridian_TWIN_ESP32
          - Meridian_TWIN_Teensy
          - Meridian_LITE_M5StackAtom
#          - Meridian_Lite_pico
      build_flags:
        description: 'Build flags'
        required: false
        type: string

jobs:
  Build_Meridian_ext_bin:
    if: github.event.inputs.board_env == 'Meridian_TWIN_Teensy'
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: ${{inputs.board_env}}
      build_flags: ${{inputs.build_flags}}
      firmware_name: ${{inputs.board_env}}
      ext_name: bin

  Build_Meridian_ext_hex:
    if: github.event.inputs.board_env != 'Meridian_TWIN_Teensy'
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      board_env: ${{inputs.board_env}}
      build_flags: ${{inputs.build_flags}}
      firmware_name: ${{inputs.board_env}}
      ext_name: hex
